// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWwsQAFlx-d2X14CoIoxB0m25EkvSvP94',
    appId: '1:532979850997:web:a04dcc229d2cdd85e56fbc',
    messagingSenderId: '532979850997',
    projectId: 'movie-app-8a440',
    authDomain: 'movie-app-8a440.firebaseapp.com',
    storageBucket: 'movie-app-8a440.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG82alQtCC1weSlcFa7KHt-e7uzzIdrTQ',
    appId: '1:532979850997:android:a5246ddc9b287187e56fbc',
    messagingSenderId: '532979850997',
    projectId: 'movie-app-8a440',
    storageBucket: 'movie-app-8a440.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7D_jYGB7-VfUgjyhXpCk1SUEXUGtv2ns',
    appId: '1:532979850997:ios:abaf74339db0810fe56fbc',
    messagingSenderId: '532979850997',
    projectId: 'movie-app-8a440',
    storageBucket: 'movie-app-8a440.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7D_jYGB7-VfUgjyhXpCk1SUEXUGtv2ns',
    appId: '1:532979850997:ios:abaf74339db0810fe56fbc',
    messagingSenderId: '532979850997',
    projectId: 'movie-app-8a440',
    storageBucket: 'movie-app-8a440.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWwsQAFlx-d2X14CoIoxB0m25EkvSvP94',
    appId: '1:532979850997:web:90215389d78ababce56fbc',
    messagingSenderId: '532979850997',
    projectId: 'movie-app-8a440',
    authDomain: 'movie-app-8a440.firebaseapp.com',
    storageBucket: 'movie-app-8a440.appspot.com',
  );
}
